const fs = require('fs');
const sys = require('sys');

function saveImage(req, res, next) {

// string generated by canvas.toDataURL()
	let img = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0'
			+ 'NAAAAKElEQVQ4jWNgYGD4Twzu6FhFFGYYNXDUwGFpIAk2E4dHDRw1cDgaCAASFOffhEIO'
			+ '3gAAAABJRU5ErkJggg==';
// strip off the data: url prefix to get just the base64-encoded bytes
	let data = img.replace(/^data:image\/\w+;base64,/, '');
	let buf = new Buffer(data, 'base64');
	fs.writeFile('image.png', buf);
}
module.exports = {
	saveImage: saveImage
};