module.exports = {
	saveImage: (req, res, next) => {
		const now = new Date().getTime(),
				name = `${now}.png`;
// string generated by canvas.toDataURL()
		let img = req.body.image;
// strip off the data: url prefix to get just the base64-encoded bytes
		let data = img.replace(/^data:image\/\w+;base64,/, '');
		let buf = new Buffer(data, 'base64');
		fs.writeFile(`${name}`, buf, (err) => {
			if (err) {
				return res.status(500).send(err);
			}
			db.saveImage(name, (err) => {
				if (err) {
					return res.status(500).send(err);
				}

				console.log('yyyy');
				res.status(201).send('eee');
			});
		});
	}
}